name: Scrape Talk Locations

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    # Give this workflow write access to THIS repo (your fork)
    permissions:
      contents: write

    steps:
      # Use latest checkout and avoid keeping default creds/remote
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas requests beautifulsoup4 geopy
          pip install --upgrade getorg

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Commit & push changes to THIS fork/branch
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Automated update of talk locations" || echo "No changes to commit"

          # Point origin at your fork and push to the current branch (main/master/etc.)
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push origin "HEAD:${{ github.ref_name }}"
